persistence:
  enabled: true
  existingClaim: pvc-grafana
adminUser: admin
adminPassword: password
service:
  type: ClusterIP
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    node-exporter-full:
      gnetId: 1860
      revision: 24
      datasource: Prometheus
    loki-logs:
      gnetId: 13639
      revision: 1
      datasource: Loki
    kubernetes-cluster:
      gnetId: 13639
      revision: 2
      datasource: Prometheus
resources:
  requests:
    memory: 200Mi
    cpu: 100m
  limits:
    memory: 400Mi
    cpu: 200m
