loki:
  enabled: true
  isDefault: true

  persistence:
    enabled: true
    storageClassName: local-static
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  auth_enabled: false

config: |
  auth_enabled: false

  server:
    http_listen_port: 3100

  ingester:
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
    chunk_idle_period: 5m
    chunk_retain_period: 30s
    max_transfer_retries: 0

  schema_config:
    configs:
      - from: 2022-01-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks

  chunk_store_config:
    max_look_back_period: 0s

  table_manager:
    retention_deletes_enabled: false
    retention_period: 0s

# Para evitar deploy com vários pods de read/write/backend
singleBinary:
  replicas: 1

backend:
  replicas: 0

write:
  replicas: 0

read:
  replicas: 0

