apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
data:
  custom.ini: |
    [server]
    http_port = 3000
    [auth.anonymous]
    enabled = true
