apiVersion: v1
kind: PersistentVolume
metadata:
  name: stack-pv-tempo
  labels:
    stack: monitoring
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: stack-sc
  local:
    path: /mnt/data/tempo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - Leo-Vostro
