apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stack-pvc-tempo
  namespace: monitoring
  labels:
    stack: monitoring
spec:
  storageClassName: stack-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      stack: monitoring
  volumeName: stack-pv-tempo # Nome do PV que foi criado
