# stack-pvc-prometheus.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stack-pvc-prometheus
  namespace: monitoring
  labels:
    stack: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: stack-sc
  selector:
    matchLabels:
      stack: monitoring
  volumeName: stack-pv-prometheus # Nome do PV que foi criado
