apiVersion: v1
kind: Service
metadata:
  name: grafana-frontend
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30000

