# pv-tempo.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tempo
spec:
  storageClassName: local-static
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/tempo

