grafana:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    storageClassName: microk8s-hostpath

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /var/lib/grafana/dashboards

  sidecar:
    datasources:
      enabled: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards

  dashboards:
    default: {}
  
  kubeControllerManager:
  service:
    ipFamilyPolicy: SingleStack
    ipFamilies:
      - IPv4

  kubeScheduler:
  service:
    ipFamilyPolicy: SingleStack
    ipFamilies:
      - IPv4
