apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage-pv
  labels:
    type: local
    app: grafana
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-config-pv
  labels:
    type: local
    app: grafana
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana-config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-datasources-pv
  labels:
    type: local
    app: grafana
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana-datasources"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboards-pv
  labels:
    type: local
    app: grafana
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana-dashboards"
