apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage-pv
  labels:
    type: local
    app: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/prometheus"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-tsdb-pv
  labels:
    type: local
    app: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/prometheus-tsdb"
