apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tempo
  namespace: monitoring
spec:
  storageClassName: local-static
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
