apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-alertmanager
  namespace: monitoring
spec:
  storageClassName: local-static
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
