apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-prom-stack-pv
spec:
  storageClassName: kube-prom-sc
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/kube-prom-stack

