apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prom-stack-pvc-grafana
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: kube-prom-sc
