apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prom-stack-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: kube-prom-sc
